# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mithorium-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter MiThoriumSSI Mi8937 Mi439_4_19 Tiare oxygen uter vince onc,$(TARGET_DEVICE)),)

endif
